### ISSUE TITLE
"Not enough space error" but installation without any errors

### ISSUE THREAD

**Issue by marekrydlewski** [parlance/ctcdecode#119]
After successful installation (I don't get any error messages, everything looks good) I got error when using `CTCBeamDecoder`, it throws exceptions even when running ` test.py`.

Error message is always the same: "not enough space" which is quite odd.
```

> Traceback (most recent call last):
>   File "test.py", line 82, in test_beam_search_decoder_3
>     model_path=lm_path)
>   File "/home/marek/anaconda3/envs/espnet/lib/python3.7/site-packages/ctcdecode/__init__.py", line 18, in __init__
>     self._num_labels)
> RuntimeError: Not enough space
```

If I pass `lm_path` to `CTCBeamDecoder` constructor it fails on line:
```

 if model_path:
     self._scorer = ctc_decode.paddle_get_scorer(alpha, beta, model_path.encode(), 
                                                                    self._labels,  self._num_labels)
```
if not, it fails on call to `ctc_decode.paddle_beam_decode`

I use pytorch in version 1.1
I've tried multiple installations but it didn't not help. I use RTX 2080, cuda 10.1 but I don't know if it's related.

Any ideas?

**Comment by SeanNaren** [comment]
What LM are you using?

**Comment by marekrydlewski** [comment]
For included `test.py` in this repo I use included arpa file. But for my usage (deepspeech.pytorch) I use LM binary generated from KenLM)

**Comment by baicaitongee** [comment]
i have the same error , @marekrydlewski .Have you solved the problem?

**Comment by Dikay1** [comment]
I meet the same error , @marekrydlewski @baicaitongee .Have you solved the problem?
