### ISSUE TITLE
Cannot allocate memory mmap failed for size 2953349384 at offset 0

### ISSUE THREAD

**Issue by baicaitongee** [parlance/ctcdecode#137]
when i run it on raspberry pi (ram 4gb），i got this:

Loading model...
Traceback (most recent call last):
  File "examples/demo-server.py", line 10, in <module>
    import beamdecode
  File "/home/pi/masr/examples/../beamdecode.py", line 29, in <module>
    blank_index,
  File "/home/pi/.local/lib/python3.7/site-packages/ctcdecode/__init__.py", line 18, in __init__
    self._num_labels)
RuntimeError: third_party/kenlm/util/mmap.cc:122 in void* util::MapOrThrow(std::size_t, bool, int, bool, int, uint64_t) threw ErrnoException because `(ret = mmap(__null, size, protect, flags, fd, offset)) == ((void *) -1)'.
Cannot allocate memory mmap failed for size 2953349384 at offset 0

**Comment by zamling** [comment]
Have a same problem! Hoping a solution
