### ISSUE TITLE
installation problem..

### ISSUE THREAD

**Issue by daniele777** [parlance/ctcdecode#180]
ERROR: Command errored out with exit status 1:
   command: /home/dani/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-fdge5ws3/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-fdge5ws3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-xn9tfdae                                      
       cwd: /tmp/pip-req-build-fdge5ws3/                                                                      
  Complete output (55 lines):                                                                                 
  /home/dani/anaconda3/lib/python3.8/distutils/extension.py:131: UserWarning: Unknown Extension options: 'package', 'with_cuda'                                                                                             
    warnings.warn(msg)                                                                                        
  running bdist_wheel                                                                                         
  /home/dani/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py:352: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.                                                                                                    
    warnings.warn(msg.format('we could not find ninja.'))                                                     
  running build                                                                                               
  running build_py                                                                                            
  creating build                                                                                              
  creating build/lib.linux-x86_64-3.8                                                                         
  creating build/lib.linux-x86_64-3.8/ctcdecode                                                               
  copying ctcdecode/__init__.py -> build/lib.linux-x86_64-3.8/ctcdecode                                       
  running build_ext                                                                                           
  Traceback (most recent call last):                                                                          
    File "<string>", line 1, in <module>                                                                      
    File "/tmp/pip-req-build-fdge5ws3/setup.py", line 113, in <module>                                        
      setup(                                                                                                  
    File "/home/dani/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup        
      return distutils.core.setup(**attrs)                                                                    
    File "/home/dani/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup                           
      dist.run_commands()                                                                                     
    File "/home/dani/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands                    
      self.run_command(cmd)                                                                                   
    File "/home/dani/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command                     
      cmd_obj.run()                                                                                           
    File "/home/dani/anaconda3/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 290, in run            
      self.run_command('build')                                                                               
    File "/home/dani/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command                      
      self.distribution.run_command(command)                                                                  
    File "/home/dani/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command                     
      cmd_obj.run()                                                                                           
    File "/home/dani/anaconda3/lib/python3.8/distutils/command/build.py", line 135, in run                    
      self.run_command(cmd_name)                                                                              
    File "/home/dani/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command                      
      self.distribution.run_command(command)                                                                  
    File "/home/dani/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command                     
      cmd_obj.run()                                                                                           
    File "/home/dani/anaconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run  
      _build_ext.run(self)                                                                                    
    File "/home/dani/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run                                                                                                             
      _build_ext.build_ext.run(self)                                                                          
    File "/home/dani/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 340, in run                
      self.build_extensions()                                                                                 
    File "/home/dani/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 361, in build_extensions                                                                                                     
      self._check_abi()                                                                                       
    File "/home/dani/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 696, in _check_abi                                                                                                           
      check_compiler_abi_compatibility(compiler)                                                              
    File "/home/dani/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 265, in check_compiler_abi_compatibility                                                                                     
      if not check_compiler_ok_for_platform(compiler):                                                        
    File "/home/dani/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 225, in check_compiler_ok_for_platform                                                                                       
      which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)                          
    File "/home/dani/anaconda3/lib/python3.8/subprocess.py", line 411, in check_output                        
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,                                        
    File "/home/dani/anaconda3/lib/python3.8/subprocess.py", line 512, in run                                 
      raise CalledProcessError(retcode, process.args,                                                         
  subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.                  
  ----------------------------------------                                                                    
  ERROR: Failed building wheel for ctcdecode

helppp

**Comment by NoCodeAvaible** [comment]
Hey, did u guy's fixed it?

**Comment by CracKCatZ** [comment]
@daniele777 did you fixed this with the way u said it in the ai hackers issue section?

**Comment by daniele777** [comment]
Unfortunally yes i can't use anaconda

**Comment by CracKCatZ** [comment]
@daniele777 think this package is not supported by conda try with a python environment

**Comment by Irislucent** [comment]
I encountered the same problem. It turns out that I didn't have g++ installed on my Debian. After installing g++, it works in my conda environment.
