### ISSUE TITLE
Unable to run the pip install . command

### ISSUE THREAD

**Issue by nausherwan-malik** [parlance/ctcdecode#224]
pip install .
Processing /home/ubuntu/Documents/CorrNet/virtualenv/ctcdecode
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/ubuntu/Documents/CorrNet/virtualenv/ctcdecode/setup.py", line 30, in <module>
          download_extract(
        File "/home/ubuntu/Documents/CorrNet/virtualenv/ctcdecode/setup.py", line 21, in download_extract
          tar.extractall("third_party/")
        File "/home/ubuntu/anaconda3/envs/corrnet/lib/python3.9/tarfile.py", line 2250, in extractall
          self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(),
        File "/home/ubuntu/anaconda3/envs/corrnet/lib/python3.9/tarfile.py", line 2313, in _extract_one
          self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
        File "/home/ubuntu/anaconda3/envs/corrnet/lib/python3.9/tarfile.py", line 2396, in _extract_member
          self.makefile(tarinfo, targetpath)
        File "/home/ubuntu/anaconda3/envs/corrnet/lib/python3.9/tarfile.py", line 2449, in makefile
          copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
        File "/home/ubuntu/anaconda3/envs/corrnet/lib/python3.9/tarfile.py", line 251, in copyfileobj
          buf = src.read(bufsize)
        File "/home/ubuntu/anaconda3/envs/corrnet/lib/python3.9/gzip.py", line 300, in read
          return self._buffer.read(size)
        File "/home/ubuntu/anaconda3/envs/corrnet/lib/python3.9/_compression.py", line 68, in readinto
          data = self.read(len(byte_view))
        File "/home/ubuntu/anaconda3/envs/corrnet/lib/python3.9/gzip.py", line 506, in read
          raise EOFError("Compressed file ended before the "
      EOFError: Compressed file ended before the end-of-stream marker was reached
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I am using python 3.9 for my code.

**Comment by cecilialeo77** [comment]
How do I fix this? I'm having the same problem.

**Comment by justlis** [comment]
I've encountered the same issue, and it has been bothering me for a week.How do I fix this?
