### ISSUE TITLE
certificate verify failed while install pip .

### ISSUE THREAD

**Issue by gmkim90** [parlance/ctcdecode#51]
When I type 'pip install .', it causes error below :
I am using python 3.6, ubuntu 14.04.
Any idea how to resolve this?

kenkim@node10:/data3/kenkim/deepspeech.pytorch/ctcdecode$ pip install .
Processing /data3/kenkim/deepspeech.pytorch/ctcdecode
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/home/kenkim/anaconda3/lib/python3.6/urllib/request.py", line 1318, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "/home/kenkim/anaconda3/lib/python3.6/http/client.py", line 1239, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/home/kenkim/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/home/kenkim/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/home/kenkim/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
        self.send(msg)
      File "/home/kenkim/anaconda3/lib/python3.6/http/client.py", line 964, in send
        self.connect()
      File "/home/kenkim/anaconda3/lib/python3.6/http/client.py", line 1400, in connect
        server_hostname=server_hostname)
      File "/home/kenkim/anaconda3/lib/python3.6/ssl.py", line 401, in wrap_socket
        _context=self, _session=session)
      File "/home/kenkim/anaconda3/lib/python3.6/ssl.py", line 808, in __init__
        self.do_handshake()
      File "/home/kenkim/anaconda3/lib/python3.6/ssl.py", line 1061, in do_handshake
        self._sslobj.do_handshake()
      File "/home/kenkim/anaconda3/lib/python3.6/ssl.py", line 683, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-w0kw5634-build/setup.py", line 55, in <module>
        os.path.join(this_file, "build.py:ffi")
      File "/home/kenkim/anaconda3/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/kenkim/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py", line 318, in __init__
      File "/home/kenkim/anaconda3/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/home/kenkim/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py", line 375, in finalize_options
      File "/home/kenkim/anaconda3/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 187, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/home/kenkim/anaconda3/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/home/kenkim/anaconda3/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "/tmp/pip-w0kw5634-build/build.py", line 24, in <module>
        'third_party/boost_1_63_0.tar.gz')
      File "/tmp/pip-w0kw5634-build/build.py", line 14, in download_extract
        out=dl_path)
      File "/home/kenkim/anaconda3/lib/python3.6/site-packages/wget-3.2-py3.6.egg/wget.py", line 526, in download
      File "/home/kenkim/anaconda3/lib/python3.6/urllib/request.py", line 248, in urlretrieve
        with contextlib.closing(urlopen(url, data)) as fp:
      File "/home/kenkim/anaconda3/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/home/kenkim/anaconda3/lib/python3.6/urllib/request.py", line 526, in open
        response = self._open(req, data)
      File "/home/kenkim/anaconda3/lib/python3.6/urllib/request.py", line 544, in _open
        '_open', req)
      File "/home/kenkim/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/home/kenkim/anaconda3/lib/python3.6/urllib/request.py", line 1361, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "/home/kenkim/anaconda3/lib/python3.6/urllib/request.py", line 1320, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-w0kw5634-build/

**Comment by ryanleary** [comment]
I think this must be an issue with your python distribution and handling SSL requests.
