### ISSUE TITLE
IOError: [Errno socket error] [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by minushuang** [parlance/ctcdecode#67]
When I git clone and type ' pip install . ', I get the following IOError:Network is unreachable ?
any solution will be appreciated.

```
root@hxh:/home/hxh/common_use/ctcdecode# python setup.py install
zip_safe flag not set; analyzing archive contents...

Installed /home/hxh/common_use/ctcdecode/.eggs/wget-3.2-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    os.path.join(this_file, "build.py:ffi")
  File "/home/hxh/anaconda2/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/hxh/anaconda2/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/hxh/anaconda2/lib/python2.7/site-packages/setuptools/dist.py", line 333, in __init__
    _Distribution.__init__(self, attrs)
  File "/home/hxh/anaconda2/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/home/hxh/anaconda2/lib/python2.7/site-packages/setuptools/dist.py", line 476, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/hxh/anaconda2/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 193, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/home/hxh/anaconda2/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/home/hxh/anaconda2/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 25, in execfile
    exec(code, glob, glob)
  File "build.py", line 22, in <module>
    'third_party/openfst-1.6.7.tar.gz')
  File "build.py", line 14, in download_extract
    out=dl_path)
  File "build/bdist.linux-x86_64/egg/wget.py", line 526, in download
  File "/home/hxh/anaconda2/lib/pyt``hon2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/home/hxh/anaconda2/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/home/hxh/anaconda2/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/home/hxh/anaconda2/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/home/hxh/anaconda2/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/home/hxh/anaconda2/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/home/hxh/anaconda2/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/home/hxh/anaconda2/lib/python2.7/httplib.py", line 1255, in connect
    HTTPConnection.connect(self)
  File "/home/hxh/anaconda2/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/home/hxh/anaconda2/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 101] Network is unreachable
```

**Comment by linrio** [comment]
@minushuang I have met the same problem? And How to fix this problem? 

```
Step12/14 : RUN git clone --recursive https://github.com/parlance/ctcdecode.git
 ---> Using cache
 ---> 716635b0cded
Step 13/14 : RUN cd ctcdecode; pip install .
 ---> Running in 8ec5d61daecc
Processing /tmp/ctcdecode
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-o5WTDh/setup.py", line 55, in <module>
        os.path.join(this_file, "build.py:ffi")
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/local/lib/python2.7/dist-packages/cffi/setuptools_ext.py", line 204, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/usr/local/lib/python2.7/dist-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/usr/local/lib/python2.7/dist-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "/tmp/pip-req-build-o5WTDh/build.py", line 22, in <module>
        'third_party/openfst-1.6.7.tar.gz')
      File "/tmp/pip-req-build-o5WTDh/build.py", line 14, in download_extract
        out=dl_path)
      File "/usr/local/lib/python2.7/dist-packages/wget.py", line 526, in download
        (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
      File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
        return opener.retrieve(url, filename, reporthook, data)
      File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
        fp = self.open(url, data)
      File "/usr/lib/python2.7/urllib.py", line 213, in open
        return getattr(self, name)(url)
      File "/usr/lib/python2.7/urllib.py", line 443, in open_https
        h.endheaders(data)
      File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
        self.send(msg)
      File "/usr/lib/python2.7/httplib.py", line 859, in send
        self.connect()
      File "/usr/lib/python2.7/httplib.py", line 1270, in connect
        HTTPConnection.connect(self)
      File "/usr/lib/python2.7/httplib.py", line 836, in connect
        self.timeout, self.source_address)
      File "/usr/lib/python2.7/socket.py", line 575, in create_connection
        raise err
    IOError: [Errno socket error] [Errno 99] Cannot assign requested address
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-o5WTDh/
```

**Comment by minushuang** [comment]
@linrio 
check the code 'build.py', download openfst-1.6.7.tar.gz and boost_1_63_0.tar manually.
------------------------------------------------------------------------------------------------

**Comment by linrio** [comment]
Okay, I add an new download-site for Chinese. And I  PR an branch for Chinese users.
